# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-29 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regressionApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropprediction',
            name='predictedPriceOne',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cropprediction',
            name='predictedPriceTwo',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cropprediction',
            name='predictedYearOne',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cropprediction',
            name='predictedYearTwo',
            field=models.FloatField(),
        ),
    ]
